instagram/post/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.post_list, name='post_list'),
    url(r'^create/$', views.post_create, name='post_create'),
    url(r'^(?P<post_pk>\d+)/$', views.post_detail, name='post_detail'),
    url(r'^(?P<post_pk>\d+)/comment_create', views.comment_create, name='comment_create'),
    url(r'^(?P<post_pk>\d+)/post_delete', views.post_delete, name='post_delete'),
    url(r'^comment/(?P<comment_pk>\d+)/delete/$', views.comment_delete, name='comment_delete'),
    url(r'^(?P<post_pk>\d+)/like-toggle/', views.post_like_toggle, name='post_like_toggle'),
]

instagram/post/models.py
from django.db import models

from django.conf import settings

class PostManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().exclude(author=None)
class Post(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL,
                               on_delete=models.SET_NULL,
                               related_name='posts',
                               blank=True,
                               null=True)
    #유저모델 이름 신경쓸 필요 X 어차피 유저모델은 하나다
    photo = models.ImageField(upload_to='post')
    created_at = models.DateTimeField(auto_now_add=True)

    objects = PostManager()

    def __str__(self):
        return f'{self.created_at}'

    class Meta:
        ordering = ['-created_at']

class PostComment(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL,
                               on_delete=models.SET_NULL,
                               blank=True,
                               null=True,
                                )
    post = models.ForeignKey(Post, related_name='comments')
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.created_at}'

    class Meta:
        ordering = ['created_at']

instagram/post/forms.py
from django import forms

from .models import Post, PostComment


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = (
            'photo',
        )

    def save(self, commit=True, *args, **kwargs):
        if not self.instance.pk and commit:
            author = kwargs.pop('author', None)
            if not author:
                raise ValueError('Author field is required')
            self.instance.author = author
        return super().save(*args, **kwargs)

class CommentForm(forms.ModelForm):
    class Meta:
        model = PostComment
        fields = (
            'content',
        )
        widgets = {
            'content': forms.TextInput(
                attrs={
                    'class': 'form-control',
                }
            )
        }

# class CommentForm(forms.Form):
#     content = forms.CharField(
#         widget=forms.TextInput(
#             attrs={
#                 'class': 'comment-form'
#             }
#         )
#     )

instagram/config/urls/views.py
from django.conf.urls import url, include
from django.contrib import admin

from .. import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.index, name='index'),
    url(r'^post/', include('post.urls.views', namespace='post')),
    url(r'^member/', include('member.urls.views', namespace='member')),
]

instagram/member/urls/views.py
from django.conf.urls import url

from .. import views

urlpatterns = [
    url(r'^signup/$', views.signup, name='signup'),
    url(r'^login/$', views.login, name='login'),
    url(r'^logout/$', views.logout, name='logout'),
    url(r'^profile/(?P<nickname>\w+)/$', views.profile, name='profile'),
    url(r'^facebook-login/$', views.facebook_login, name='facebook_login'),
    url(r'^follow/(?P<nickname>\w+)/$', views.follow, name='follow'),
    url(r'^front-facebook-login/$', views.FrontFacebookLogin.as_view(), name='front-facebook-login'),
]

instagram/post/urls/views.py
from django.conf.urls import url
from .. import views

urlpatterns = [
    url(r'^$', views.post_list, name='post_list'),
    url(r'^create/$', views.post_create, name='post_create'),
    url(r'^(?P<post_pk>\d+)/$', views.post_detail, name='post_detail'),
    url(r'^(?P<post_pk>\d+)/comment_create', views.comment_create, name='comment_create'),
    url(r'^(?P<post_pk>\d+)/post_delete', views.post_delete, name='post_delete'),
    url(r'^comment/(?P<comment_pk>\d+)/delete/$', views.comment_delete, name='comment_delete'),
    url(r'^(?P<post_pk>\d+)/like-toggle/', views.post_like_toggle, name='post_like_toggle'),
]

instagram/post/views/comment.py
from django.core.exceptions import PermissionDenied
from django.shortcuts import redirect, get_object_or_404

from ..forms import CommentForm
from ..models import Post, PostComment

__all__ = (
    'comment_create',
    'comment_delete',
)

def comment_create(request, post_pk):
    if not request.user.is_authenticated:
        return redirect('member:login')
    post = get_object_or_404(Post, pk=post_pk)
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.author = request.user
            comment.post = post
            comment.save()

        next_path = request.GET.get('next', '').strip()
        if next_path:
            return redirect(next_path)
        return redirect('post:post_detail', post_pk=post.pk)

def comment_delete(request, comment_pk):
    next_path = request.GET.get('next', '').strip()
    if request.method == 'POST':
        comment = get_object_or_404(PostComment, pk=comment_pk)
        if comment.author == request.user:
            comment.delete()
            if next_path:
                return redirect(next_path)
            return redirect('post:post_detail', post_pk=comment.post.pk)
        else:
            raise PermissionDenied('작성자가 아닙니다')

instagram/post/views/post.py
from django.core.exceptions import PermissionDenied
from django.shortcuts import render, redirect, get_object_or_404

from member.decorators import login_required
from ..forms import PostForm, CommentForm
from ..models import Post

__all__ = (
    'post_list',
    'post_create',
    'post_detail',
    'post_delete',
    'post_like_toggle',
)

def post_list(request):
    """모든 포스트목록 리턴,
    템프릿은 'post/post_list.html'을 사용
    """
    # posts = Post.objects.exclude(author=None)
    posts = Post.objects.all()
    comment_form = CommentForm()
    context = {
        'posts': posts,
        'comment_form': comment_form,
    }
    return render(request, 'post/post_list.html', context)


def post_create(request):
    if not request.user.is_authenticated:
        return redirect('member:login')

    # Form 사용 할 때!
    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            return redirect('post:post_list')
    else:
        # GET 요청인 경우, 빈 PostForm인스턴스를 생성해서 탬플릿에 전달
        form = PostForm()
    context = {
        'form': form,
    }
    return render(request, 'post/post_create.html', context)


def post_detail(request, post_pk):
    # post = get_object_or_404(Post.objects.exclude(author=None), pk=post_pk)
    post = get_object_or_404(Post, pk=post_pk)
    comment_form = CommentForm()
    context = {
        'post': post,
        'comment_form': comment_form,
    }
    return render(request, 'post/post_detail.html', context)


def post_delete(request, post_pk):
    if request.method == 'POST':
        post = get_object_or_404(Post, pk=post_pk)
        if post.author == request.user:
            post.delete()
            return redirect('post:post_list')
        else:
            raise PermissionDenied


@login_required
def post_like_toggle(request, post_pk):
    if not request.user.is_authenticated:
        return render(request, 'member:login')
    next_path = request.GET.get('next')
    if request.method == 'POST':
        post = get_object_or_404(Post, pk=post_pk)
        user = request.user

        filtered_like_posts = user.like_posts.filter(pk=post_pk)
        if filtered_like_posts.exists():
            user.like_posts.remove(post)
        else:
            user.like_posts.add(post)
        if next_path:
            return redirect(next_path)
        return redirect('post:post_detail', post_pk=post_pk)

instagram/templates/include/form-horizontal.html
<form action="" method="POST" enctype="multipart/form-data" class="form-horizontal">
	{% csrf_token %}
	{% for field in form %}
	<div class="form-group{% if field.errors %} has-error{% endif %}">
		<label
			for="{{ field.auto_id }}"
			class="col-xs-2 control-label">
			{{ field.label }}
		</label>
		<div class="col-xs-10">
			{{ field }}
			{% if field.errors %}
				{% for error in field.errors %}
				<span class="help-block">{{ error }}</span>
				{% endfor %}
			{% endif %}
		</div>
	</div>
	{% endfor %}
	{% if form.non_field_errors %}
		{% for error in form.non_field_errors %}
		<p class="text-danger">{{ error }}</p>
		{% endfor %}
	{% endif %}
	<button class="btn btn-primary btn-block">{{ submit_text }}</button>
</form>

instagram/templates/include/post.html
<div id="post-{{ post.pk }}" class="panel panel-default post">
    <div class="panel-heading"><a href="{% url 'member:profile' nickname=post.author.nickname %}"><span>{{ post.author.nickname}}</span></a>
        {% if post.author == user %}
        <form action="{% url 'post:post_delete' post_pk=post.pk %}" style="display: inline-block" method="post">
            {% csrf_token %}
            <button class="btn btn-danger btn-xs">삭제</button>
        </form>
        {% endif %}
    </div>

    <div class="panel-body">
        <a href="{% url 'post:post_detail' post_pk=post.pk %}">
            <img src="{{ post.photo.url }}" class="img-post">
        </a>
        <div class="body-content">
            <div class="btn-container">
				<form action="{% url 'post:post_like_toggle' post_pk=post.pk %}?next=
						{% if post_type == 'list' %}
							{% url 'post:post_list' %}#post-{{ post.pk }}
						{% elif post_type == 'detail' %}
							{% url 'post:post_detail' post_pk=post.pk %}
						{% endif %}" method="POST">
					{% csrf_token %}
					<button class="btn btn-default border-none" aria-label="Like button">
					  <span
						  class="glyphicon
						    {% if post in user.like_posts.all %}
						      glyphicon-heart
								{% else %}
									glyphicon-heart-empty
								{% endif %}"
						  aria-hidden="true"></span>
					</button>
				</form>
			</div>
            <ul id="post-comments-{{ post.pk }}">
                {% for comment in post.comments.all %}
                <li><span style="font-weight: bold"> {{ comment.content }}</span> commented by {{ comment.author.nickname }}
                    {% if comment.author == user %}
                    <form action="{% url 'post:comment_delete' comment_pk=comment.pk %}?next=
						{% if post_type == 'list' %}
							{% url 'post:post_list' %}#post-{{ post.pk }}
						{% elif post_type == 'detail' %}
							{% url 'post:post_detail' post_pk=post.pk %}
						{% endif %}"
                      method="post" style="display: inline-block">
                    {% csrf_token %}
                    <button class="btn btn-danger btn-xs">삭제</button>
                </form>
					{% endif %}
                </li>
                {% endfor %}
            </ul>
            <form
                    action="{% url 'post:comment_create' post_pk=post.pk %}?next={% if post_type == 'list' %}/post/#post-comments-{{ post.pk }}{% elif post_type == 'detail' %}{% url 'post:post_detail' post_pk=post.pk %}{% endif %}"
                    method="POST">
                {% csrf_token %}
                {{ comment_form.content }}
                <button class="btn-primary btn">댓글달기</button>
            </form>

        </div>
    </div>
</div>